@startuml
title get installment list from content provider

Actor User
box "Third Party App" #def2e7
participant ThirtyPartyApp #d8e4fa
end box
	box "SDK Integration" #7fffff
participant PaymentFlowImpl
end box
box "SmartPos App" #LightBlue
participant ContentProvider #d8e4fa
participant PaymentFlow #d8e4fa
end box
box "Smart FCU" #ffc0c0
participant InitializationService
participant InstallmentContainer
end box

User -> ThirtyPartyApp : paymentMethod()
ThirtyPartyApp -> PaymentFlowImpl: getInstallmentsAmount()
alt paymentMethodIsCreditCard
PaymentFlowImpl -> PaymentFlowImpl : isCreditCard
activate PaymentFlowImpl
PaymentFlowImpl -> ContentProvider : GetInstallmentByAmountUseCase()
deactivate PaymentFlowImpl
activate ContentProvider #d8e4fa
end alt
alt#Gold #Orange getInstallmentsAmountNotIsEmpty
    ContentProvider -> ContentProvider : installmentIsNotEmpty
    deactivate ContentProvider #d8e4fa
    ContentProvider -> InitializationService : getInstallment()
    deactivate ContentProvider
    activate InitializationService
    ContentProvider <-- InitializationService: HasMap<String, Float>()
    deactivate InitializationService
    else #Gold getInstallmentsAmountIsEmpty
        ContentProvider -> InstallmentContainer : GetInstallmentUseCase()
        activate InstallmentContainer
        ContentProvider <-- InstallmentContainer : HasMap<String, Float>()
        deactivate InstallmentContainer
end
ContentProvider -> ContentProvider : createCursor()
activate ContentProvider #d8e4fa
ThirtyPartyApp <-- ContentProvider : List<InstallmentAmount>
deactivate ContentProvider
ThirtyPartyApp -> ThirtyPartyApp: selectInstallment
activate ThirtyPartyApp #d8e4fa
alt isPaymentFlowWhitInstallment
	ThirtyPartyApp -> PaymentFlow : launchPaymentFlowActivity(PaymentFlowData, this)
    deactivate ThirtyPartyApp
    activate PaymentFlow #d8e4fa
    PaymentFlowImpl <-- PaymentFlow: PaymentResponse
    deactivate PaymentFlow
    activate PaymentFlowImpl
    ThirtyPartyApp <-- PaymentFlowImpl: resultPaymentFlow
    deactivate PaymentFlowImpl
    activate ThirtyPartyApp #d8e4fa
end
User <-- ThirtyPartyApp: notify result payment
deactivate ThirtyPartyApp
@enduml